# Site settings
title: Robert Finnegan
email: Robert.N.Finnegan@gmail.com
description: "Robert Finnegan's personal website."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2952a4
  secondary: 004d4d
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: Robert.N.Finnegan@gmail.com
  - title: linkedin
    url: http://www.linkedin.com/in/robertfinnegan
  - title: github
    url: http://github.com/rnfinnegan

# Build settings
markdown: kramdown
permalink: pretty
