# Site settings
title: Kasper Marstal
email: kaspermarstal@gmail.com
description: "Kasper Marstal's personal website."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3E606F
  secondary: 91AA9D
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: kaspermarstal@gmail.com
  - title: linkedin
    url: http://www.linkedin.com/in/kaspermarstal
  - title: github
    url: http://github.com/kaspermarstal
  - title: stack-overflow
    url: http://stackoverflow.com/users/346365/kasper-marstal

# Build settings
markdown: kramdown
permalink: pretty
